### ISSUE TITLE
make a CITATION.cff?

### ISSUE THREAD

**Issue by hyphaltip** [bioperl/bioperl-live#368]
for zenodo it might be good to make a citation link for future releases. needs to be more than just the old paper but all the new contributors?

https://github.com/bioperl/bioperl-live/new/master?filename=CITATION.cff

https://citation-file-format.github.io/

[CITATION.cff](https://citation-file-format.github.io/) files are plain text files with human- and machine-readable citation information for software. Code developers can include them in their repositories to let others know how to correctly cite their software.

An example of the CITATION.cff for this release can be found below:

```
cff-version: 1.1.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Joe
    given-names: Johnson
    orcid: https://orcid.org/0000-0000-0000-0000
title: bioperl/bioperl-live: BioPerl 1.7.2
version: release-1-7-2
date-released: 2017-12-18
```
